services:
  vuzon:
    image: ghcr.io/svnz0x/vuzon-docker
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || curl -fsS http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
